//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.12.04 at 10:55:57 PM EET
//

package entity;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for employee complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="employee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}person"/>
 *         &lt;element ref="{}data"/>
 *         &lt;element name="modifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "employee", propOrder = {
		"person", "data", "modifiedDate" }) public class Employee {

	@Override public String toString() {
		return String.format(
				"Employee [id=%s, person=%s, data=%s, modifiedDate=%s]", id, person,
				data, modifiedDate);
	}

	@XmlElement(required = true) protected Person person;
	@XmlElement(required = true) protected Data data;
	@XmlElement(required = true) protected Date modifiedDate;
	@XmlAttribute protected Long id;

	/**
	 * Gets the value of the person property.
	 * 
	 * @return possible object is {@link Person }
	 * 
	 */
	public Person getPerson() {
		return person;
	}

	/**
	 * Sets the value of the person property.
	 * 
	 * @param value
	 *        allowed object is {@link Person }
	 * 
	 */
	public void setPerson(Person value) {
		this.person = value;
	}

	/**
	 * Gets the value of the data property.
	 * 
	 * @return possible object is {@link Data }
	 * 
	 */
	public Data getData() {
		return data;
	}

	/**
	 * Sets the value of the data property.
	 * 
	 * @param value
	 *        allowed object is {@link Data }
	 * 
	 */
	public void setData(Data value) {
		this.data = value;
	}

	/**
	 * Gets the value of the modifiedDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getModifiedDate() {
		return modifiedDate;
	}

	/**
	 * Sets the value of the modifiedDate property.
	 * 
	 * @param value
	 *        allowed object is {@link Date }
	 * 
	 */
	public void setModifiedDate(Date value) {
		this.modifiedDate = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *        allowed object is {@link Long }
	 * 
	 */
	public void setId(Long value) {
		this.id = value;
	}
	public Employee() {}
	public Employee(Long id, Person person, Data data, Date modifiedDate) {
		super();
		this.id = id;
		this.person = person;
		this.data = data;
		this.modifiedDate = modifiedDate;
	}

}
