//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.1.2-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2010.12.04 at 10:55:57 PM EET
//

package entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map.Entry;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.google.appengine.repackaged.com.google.common.base.Preconditions;
import com.google.appengine.repackaged.com.google.common.collect.ImmutableMap;
import com.google.appengine.repackaged.com.google.common.collect.Maps;

// TODO: Auto-generated Javadoc
/**
 * <p>
 * Java class for raport complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="raport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="depWageSum" type="{}stringToDoubleMapAdapter" minOccurs="0"/>
 *         &lt;element name="grandTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Margus Martsepp
 * @version $Revision: 1.0 $
 */
@XmlAccessorType(XmlAccessType.FIELD) @XmlType(name = "raport", propOrder = {
		"depWageSum", "grandTotal" }) @XmlRootElement public class Report implements
		Serializable {
	/**
	 * <p>
	 * This is stable compatibility validator. This is used among other things to
	 * determine if a deserialized file is compatible with this class.
	 * <p>
	 * For more information about why this class is useful, check <a href=
	 * "http://mindprod.com/jgloss/serialization.html#SERIALVERSIONUID" >this</a>
	 * out.
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Instantiates a new report.
	 */
	public Report() {}

	/**
	 * Instantiates a new report.
	 * 
	 * @param depWageSum
	 *        the dep wage sum
	 * @param id
	 *        the id
	 * 
	 * 
	 * @throws NullPointerException
	 *         the null pointer exception
	 */
	public Report(final HashMap<String, Double> depWageSum, final Long id)
			throws NullPointerException {
		super();
		this.id = Preconditions.checkNotNull(id);
		this.setDepWageSum(depWageSum);
	}

	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override public String toString() {
		return String.format("Report [id=%s, depWageSum=%s, grandTotal=%s]", id,
				depWageSum, grandTotal);
	}

	/** The dep wage sum. */
	protected HashMap<String, Double> depWageSum = Maps.newHashMap();

	/** The bd. */
	transient private BigDecimal bd = BigDecimal.ZERO;

	/** The grand total. */
	protected double grandTotal = 0d;

	/** The id. */
	@XmlAttribute protected Long id;

	/**
	 * Gets the value of the depWageSum property.
	 * 
	 * 
	 * 
	 * 
	 * @return possible object is {@link ImmutableMap<String, Double> }
	 */
	public ImmutableMap<String, Double> getDepWageSum() {
		return ImmutableMap.copyOf(depWageSum);
	}

	/**
	 * Gets the value of the grandTotal property.
	 * 
	 * 
	 * 
	 * @return the grand total
	 */
	public double getGrandTotal() {
		return grandTotal;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * 
	 * 
	 * 
	 * @return possible object is {@link Long }
	 */
	public Long getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *        allowed object is {@link Long }
	 * 
	 */
	public void setId(Long value) {
		Preconditions.checkNotNull(value);
		this.id = value;
	}

	/**
	 * Sets the dep wage sum. This will also update current {@link #grandTotal}.
	 * Can be referred to as reset and bulk push.
	 * 
	 * @param depWageSum
	 *        the dep wage sum
	 * 
	 * 
	 * @throws NullPointerException
	 *         the null pointer exception
	 */
	public synchronized void setDepWageSum(
			final HashMap<String, Double> depWageSum) throws NullPointerException {
		Preconditions.checkNotNull(depWageSum);
		synchronized (this.depWageSum) {
			this.depWageSum.clear();
			this.grandTotal = 0;
			this.bd = BigDecimal.ZERO;
		}
		for (Entry<String, Double> elem : depWageSum.entrySet()) {
			try {
				push(elem.getKey(), elem.getValue());
			} catch (Exception e) {
				System.err.println(elem + " was invalid.");
			}
		}
	}

	/**
	 * Push.
	 * 
	 * @param departmentTitle
	 *        the department title
	 * @param hourRate
	 *        the hour rate
	 * 
	 * 
	 * 
	 * @throws NullPointerException
	 *         the null pointer exception * @throws IllegalArgumentException the
	 *         illegal argument exception
	 */
	public synchronized void push(
			final String departmentTitle, final Double hourRate) throws NullPointerException,
			IllegalArgumentException {
		Preconditions.checkNotNull(departmentTitle);
		Preconditions.checkNotNull(hourRate);
		Preconditions.checkState(hourRate > 0);

		bd = bd.add(BigDecimal.valueOf(hourRate));
		grandTotal = bd.doubleValue();
		synchronized (this.depWageSum) {
			if (this.depWageSum.containsKey(departmentTitle)) //
			this.depWageSum.put(departmentTitle,
					this.depWageSum.get(departmentTitle) + hourRate);
			else this.depWageSum.put(departmentTitle, hourRate);
		}
	}
}
