// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify this file
 * See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package entity.builder;

import entity.CompensationDateSpan;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * The Class CompensationDateSpanBuilder.
 */
public class CompensationDateSpanBuilder extends
		CompensationDateSpanBuilderBase<CompensationDateSpanBuilder> {
	
	/**
	 * Compensation date span.
	 *
	 * @return the compensation date span builder
	 */
	public static CompensationDateSpanBuilder compensationDateSpan() {
		return new CompensationDateSpanBuilder();
	}

	/**
	 * Instantiates a new compensation date span builder.
	 */
	public CompensationDateSpanBuilder() {
		super(new CompensationDateSpan());
	}

	/**
	 * Builds the.
	 *
	 * @return the compensation date span
	 */
	public CompensationDateSpan build() {
		return getInstance();
	}
}

class CompensationDateSpanBuilderBase<GeneratorT extends CompensationDateSpanBuilderBase<GeneratorT>> {
	private CompensationDateSpan instance;

	protected CompensationDateSpanBuilderBase(CompensationDateSpan aInstance) {
		instance = aInstance;
	}

	protected CompensationDateSpan getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked") public GeneratorT withStart(Date aValue) {
		instance.setStart(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withEnd(Date aValue) {
		instance.setEnd(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withCompensated(
			boolean aValue) {
		instance.setCompensated(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}
}
