// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify this file
 * See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package entity.builder;

import entity.ContactInfo;

// TODO: Auto-generated Javadoc
/**
 * The Class ContactInfoBuilder.
 */
public class ContactInfoBuilder extends
		ContactInfoBuilderBase<ContactInfoBuilder> {
	
	/**
	 * Contact info.
	 *
	 * @return the contact info builder
	 */
	public static ContactInfoBuilder contactInfo() {
		return new ContactInfoBuilder();
	}

	/**
	 * Instantiates a new contact info builder.
	 */
	public ContactInfoBuilder() {
		super(new ContactInfo());
	}

	/**
	 * Builds the.
	 *
	 * @return the contact info
	 */
	public ContactInfo build() {
		return getInstance();
	}
}

class ContactInfoBuilderBase<GeneratorT extends ContactInfoBuilderBase<GeneratorT>> {
	private ContactInfo instance;

	protected ContactInfoBuilderBase(ContactInfo aInstance) {
		instance = aInstance;
	}

	protected ContactInfo getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked") public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}
}
