// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify this file
 * See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package entity.builder;

import entity.Data;
import java.util.Date;

// TODO: Auto-generated Javadoc
/**
 * The Class DataBuilder.
 */
public class DataBuilder extends DataBuilderBase<DataBuilder> {
	
	/**
	 * Data.
	 *
	 * @return the data builder
	 */
	public static DataBuilder data() {
		return new DataBuilder();
	}

	/**
	 * Instantiates a new data builder.
	 */
	public DataBuilder() {
		super(new Data());
	}

	/**
	 * Builds the.
	 *
	 * @return the data
	 */
	public Data build() {
		return getInstance();
	}
}

class DataBuilderBase<GeneratorT extends DataBuilderBase<GeneratorT>> {
	private Data instance;

	protected DataBuilderBase(Data aInstance) {
		instance = aInstance;
	}

	protected Data getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked") public GeneratorT withCreditCard(String aValue) {
		instance.setCreditCard(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withOccupationTitle(
			String aValue) {
		instance.setOccupationTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withDepartmentTitle(
			String aValue) {
		instance.setDepartmentTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withHireDate(Date aValue) {
		instance.setHireDate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withHourRate(double aValue) {
		instance.setHourRate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}
}
