// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify this file
 * See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package entity.builder;

import entity.ContactInfo;
import entity.Person;
import javax.xml.datatype.XMLGregorianCalendar;

// TODO: Auto-generated Javadoc
/**
 * The Class PersonBuilder.
 */
public class PersonBuilder extends PersonBuilderBase<PersonBuilder> {
	
	/**
	 * Person.
	 *
	 * @return the person builder
	 */
	public static PersonBuilder person() {
		return new PersonBuilder();
	}

	/**
	 * Instantiates a new person builder.
	 */
	public PersonBuilder() {
		super(new Person());
	}

	/**
	 * Builds the.
	 *
	 * @return the person
	 */
	public Person build() {
		return getInstance();
	}
}

class PersonBuilderBase<GeneratorT extends PersonBuilderBase<GeneratorT>> {
	private Person instance;

	protected PersonBuilderBase(Person aInstance) {
		instance = aInstance;
	}

	protected Person getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked") public GeneratorT withIsMale(boolean aValue) {
		instance.setIsMale(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withBirthday(
			XMLGregorianCalendar aValue) {
		instance.setBirthday(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withICi(ContactInfo aValue) {
		instance.setICi(aValue);

		return (GeneratorT) this;
	}

	public ICiContactInfoBuilder withICi() {
		ContactInfo obj = new ContactInfo();

		withICi(obj);

		return new ICiContactInfoBuilder(obj);
	}

	@SuppressWarnings("unchecked") public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	public class ICiContactInfoBuilder extends
			ContactInfoBuilderBase<ICiContactInfoBuilder> {
		public ICiContactInfoBuilder(ContactInfo aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked") public GeneratorT endICi() {
			return (GeneratorT) PersonBuilderBase.this;
		}
	}

	public static class ContactInfoBuilderBase<GeneratorT extends ContactInfoBuilderBase<GeneratorT>> {
		private ContactInfo instance;

		protected ContactInfoBuilderBase(ContactInfo aInstance) {
			instance = aInstance;
		}

		protected ContactInfo getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked") public GeneratorT withId(Long aValue) {
			instance.setId(aValue);

			return (GeneratorT) this;
		}
	}
}
