// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator Do not modify this file
 * See generator home page at:
 * http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package entity.builder;

import entity.Raport;
import java.util.HashMap;

// TODO: Auto-generated Javadoc
/**
 * The Class RaportBuilder.
 */
public class RaportBuilder extends RaportBuilderBase<RaportBuilder> {
	
	/**
	 * Raport.
	 *
	 * @return the raport builder
	 */
	public static RaportBuilder raport() {
		return new RaportBuilder();
	}

	/**
	 * Instantiates a new raport builder.
	 */
	public RaportBuilder() {
		super(new Raport());
	}

	/**
	 * Builds the.
	 *
	 * @return the raport
	 */
	public Raport build() {
		return getInstance();
	}
}

class RaportBuilderBase<GeneratorT extends RaportBuilderBase<GeneratorT>> {
	private Raport instance;

	protected RaportBuilderBase(Raport aInstance) {
		instance = aInstance;
	}

	protected Raport getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked") public GeneratorT withDepWageSum(
			HashMap<String, Double> aValue) {
		instance.setDepWageSum(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withGrandTotal(double aValue) {
		instance.setGrandTotal(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked") public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}
}
